### ISSUE TITLE
Create documentation with description of each class/function

### ISSUE THREAD

**Issue by vemuriPradyumna** [NCSU-Fall-2022-SE-Project-Team-11/XpensAuditor---Group-11#16]

**Comment by Surya-06** [comment]
NOTE:
As a part of the rubrics, I think this task should take care of the following items. Let me know if there are any issues:
1. Docs: how: for common use cases X,Y,Z mini-tutorials showing worked examples on how to do X,Y,Z	doc page entries
2. Docs: why: docs tell a story, motivate the whole thing, deliver a punchline that makes you want to rush out and use the thing

For #1, I think our video covers the use-cases we want to exhibit and we can add a written version of the same in the readme.

For #2, I think the ReadMe file does communicate our motive behind doing this and the expectation we have out of this project. We can try to refine this further to make it communicate our intent better.

**Comment by Surya-06** [comment]
Creating tasks for getting the docs structure setup and for hosting the documents.

**Comment by Surya-06** [comment]
Closing this since we have added comments to all the classes.
