### ISSUE TITLE
Data Analysis button gives "to be updated in later versions". We can add Data Visualizations of historic data here

### ISSUE THREAD

**Issue by kaushikjadhav01** [NCSU-Fall-2022-SE-Project-Team-11/XpensAuditor---Group-11#27]

**Comment by harshitha-ready-to-code** [comment]
Have linked the visualization page to the ANALYSIS button.
When opted Analysis on the home page, it navigates to the visualization page where the user is given 2 options to visualize his expenses 
one with Daywise visualization in a month - input as month and year
another with month-wise Visualization - input as from - month, year, and To-month and year
When opted any of these options it will be navigated to a page that gives Bar graph of the expenses opted
